### PR TITLE
Lastline: Feature - Action for Artifact download

### PR DESCRIPTION
**Pull request by Benni0**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue. (new library added functionality for artifact download)
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [x] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with. (file does not exist)
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by Benni0** [comment]
The file analysis_apiclient.py is a 1:1 copy from https://user.lastline.com/analysis/api-docs/html/analysis_client.html
I've updated the file because the current version doesn't implement `get_report_artifact`.
I'm not sure if this file should be reformatted.

**Comment by aparekh-crest** [comment]
Hi @Benni0 ,
I have made the changes as per our coding standards.
Can we change `min_phantom_version` to `6.1.0` as per our best pratice?

**Comment by Benni0** [comment]
Hi @aparekh-crest,
thank you for your changes.
From my point of view you can change the `min_phantom_version`, I haven't modified it because it doesn't affect my change.

**Comment by aparekh-crest** [comment]
Hi @Benni0 ,
In lastline.json [line no. 40](https://github.com/splunk-soar-connectors/lastline/pull/4/files#diff-d930a9f3911c76f7e5b9f331842fbe836a9c72420b5e16877eab2660b4350c33R40) **timeout** parameter's default value is 120 seconds, but from connector [Line no. 411](https://github.com/splunk-soar-connectors/lastline/pull/4/files#diff-d317cd1e9ab3b29db7a336128d6add45a9a86dec3cc65c6f87599962255be64fR411) it is taking 300 seconds by default.
Could you please verify and confirm which one is correct?

**Comment by Benni0** [comment]
Hi @aparekh-crest,

I can confirm this behavior and I think this definition is ambiguous but as the `timeout` parameter is required, the value of `LASTLINE_MAX_TIMEOUT_DEF_SECS` should never be used.
As this part isn't affected by my change, I haven't recognized this.
I would recommend to set the value of `LASTLINE_MAX_TIMEOUT_DEF_SECS` to 120. It would also be possible to get the value by access the dictionary value directly by the key (`config[LASTLINE_JSON_POLL_TIMEOUT_SECS]`) as the value is required, which would require more refactoring. I've no opinion which version makes more sense.

In our setup we set the timeout to 180 seconds, which seems sufficient for us.

**Review by achandya-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
